version: '2'
services:
  db:
    image: mysql:5.6
    command: --character-set-server=utf8 --collation-server=utf8_bin
    container_name: test_db_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: trac
      MYSQL_USER: trac
      MYSQL_PASSWORD: yourpassword

  App:
    depends_on:
     - db
    image: trac
    container_name: blitz_App_1
    ports:
     - "8098:8098"
    restart: always
    environment:
      MYSQL_DATABASE: db:3306
      MYSQL_PASSWORD: yourpassword
    links:
     - db

